"""Copy the TaskNet SQLite database into PostgreSQL so it can be browsed in
pgAdmin / DBeaver / psql. Recreates every table (columns, primary keys,
UNIQUE constraints, foreign keys, views, the computed users.full_name, and
the append-only audit triggers) and copies all rows.

The running services still read and write SQLite; run this again to refresh
the PostgreSQL copy. It replaces everything in the target schema.

Run inside a backend container (it can reach the `postgres` service):
    docker exec tasknet_auth python tools/sqlite_to_postgres.py

Environment:
    SQLITE_PATH   default: tasknet.db
    PG_DSN        default: postgresql://tasknet:tasknet@postgres:5432/tasknet
    PG_SCHEMA     default: public
"""
import os
import sqlite3
import sys
from datetime import datetime

import psycopg2
from psycopg2.extras import execute_values

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from database import FULL_NAME_EXPR  # noqa: E402

SQLITE_PATH = os.getenv("SQLITE_PATH", "tasknet.db")
PG_DSN = os.getenv("PG_DSN", "postgresql://{u}:{p}@postgres:5432/{d}".format(
    u=os.getenv("POSTGRES_USER", "tasknet"), p=os.getenv("POSTGRES_PASSWORD", "tasknet"),
    d=os.getenv("POSTGRES_DB", "tasknet")))
SCHEMA = os.getenv("PG_SCHEMA", "public")

# Computed columns (SQLite VIRTUAL -> PostgreSQL STORED, same expression).
GENERATED = {("users", "full_name"): FULL_NAME_EXPR}
APPEND_ONLY = ("audit_log", "audit_log_changes")


def q(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _parses(value, kind: str) -> bool:
    if value is None:
        return True
    if not isinstance(value, str):
        return False
    v = value.strip().replace("Z", "")
    try:
        if kind == "date":
            datetime.strptime(v, "%Y-%m-%d")
        else:
            datetime.fromisoformat(v)
        return True
    except ValueError:
        return False


def pg_type(lite, table: str, col: str, decl: str) -> str:
    d = (decl or "").upper()
    if "INT" in d:
        return "bigint"
    if any(t in d for t in ("REAL", "FLOA", "DOUB", "NUMERIC", "DECIMAL")):
        return "double precision"
    if "BLOB" in d:
        return "bytea"
    if "TIMESTAMP" in d or "DATETIME" in d or d == "DATE":
        kind = "date" if d == "DATE" else "timestamp"
        values = [r[0] for r in lite.execute(f"SELECT {q(col)} FROM {q(table)}")]
        return kind if all(_parses(v, kind) for v in values) else "text"
    return "text"


def main():
    lite = sqlite3.connect(f"file:{SQLITE_PATH}?mode=ro", uri=True)
    pg = psycopg2.connect(PG_DSN)
    pg.autocommit = False
    cur = pg.cursor()
    cur.execute(f"DROP SCHEMA IF EXISTS {q(SCHEMA)} CASCADE")
    cur.execute(f"CREATE SCHEMA {q(SCHEMA)}")
    cur.execute(f"SET search_path TO {q(SCHEMA)}")

    tables = [r[0] for r in lite.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' "
        "AND name NOT LIKE '\\_%' ESCAPE '\\' ORDER BY name")]
    meta = {}
    for t in tables:
        cols = lite.execute(f"PRAGMA table_xinfo({q(t)})").fetchall()
        # cid, name, type, notnull, dflt, pk, hidden
        pk = [c[1] for c in sorted(cols, key=lambda c: c[5]) if c[5]]
        defs, copy_cols = [], []
        for _cid, name, decl, notnull, dflt, pkpos, hidden in cols:
            if hidden in (2, 3):
                expr = GENERATED.get((t, name))
                if expr:
                    defs.append(f"{q(name)} text GENERATED ALWAYS AS ({expr}) STORED")
                continue
            typ = pg_type(lite, t, name, decl)
            if pk == [name] and typ == "bigint":
                defs.append(f"{q(name)} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            else:
                part = f"{q(name)} {typ}"
                if notnull:
                    part += " NOT NULL"
                if dflt and dflt.upper() == "CURRENT_TIMESTAMP" and typ in ("timestamp", "text"):
                    part += " DEFAULT CURRENT_TIMESTAMP"
                elif dflt and dflt.lstrip("-").replace(".", "", 1).isdigit():
                    part += f" DEFAULT {dflt}"
                elif dflt and dflt.startswith("'") and dflt.endswith("'"):
                    part += f" DEFAULT {dflt}"
                defs.append(part)
            copy_cols.append(name)
        if len(pk) > 1:
            defs.append(f"PRIMARY KEY ({', '.join(q(c) for c in pk)})")
        for idx in lite.execute(f"PRAGMA index_list({q(t)})").fetchall():
            # seq, name, unique, origin (u = UNIQUE constraint, c = CREATE INDEX, pk)
            if idx[2] and idx[3] == "u":
                icols = [r[2] for r in lite.execute(f"PRAGMA index_info({q(idx[1])})")]
                defs.append(f"UNIQUE ({', '.join(q(c) for c in icols)})")
        cur.execute(f"CREATE TABLE {q(t)} (\n  " + ",\n  ".join(defs) + "\n)")
        meta[t] = (copy_cols, pk)

    # Rows (identity columns accept explicit ids: GENERATED BY DEFAULT).
    counts = {}
    for t, (copy_cols, _pk) in meta.items():
        rows = lite.execute(
            f"SELECT {', '.join(q(c) for c in copy_cols)} FROM {q(t)}").fetchall()
        if rows:
            execute_values(cur, f"INSERT INTO {q(t)} ({', '.join(q(c) for c in copy_cols)}) VALUES %s",
                           rows, page_size=500)
        counts[t] = len(rows)
        if meta[t][1] == ["id"]:
            cur.execute(f"SELECT setval(pg_get_serial_sequence('{q(t)}', 'id'), "
                        f"COALESCE((SELECT MAX(id) FROM {q(t)}), 0) + 1, false)")

    # Foreign keys. NOT VALID: enforced for new rows without failing on any
    # legacy row the SQLite file already carries.
    fk_count = 0
    for t in meta:
        fks = {}
        for _id, seq, ref, frm, to, _upd, on_delete, _match in lite.execute(
                f"PRAGMA foreign_key_list({q(t)})"):
            fks.setdefault(_id, {"ref": ref, "from": [], "to": [], "del": on_delete})
            fks[_id]["from"].append(frm)
            fks[_id]["to"].append(to or "id")
        for n, fk in fks.items():
            if fk["ref"] not in meta:
                continue
            action = "" if fk["del"] in (None, "NO ACTION") else f" ON DELETE {fk['del']}"
            cur.execute(
                f"ALTER TABLE {q(t)} ADD CONSTRAINT {q(f'fk_{t}_{n}')} FOREIGN KEY "
                f"({', '.join(q(c) for c in fk['from'])}) REFERENCES {q(fk['ref'])} "
                f"({', '.join(q(c) for c in fk['to'])}){action} NOT VALID")
            fk_count += 1

    # Regular indexes.
    for name, t, sql in lite.execute(
            "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"):
        if t in meta:
            cur.execute(sql.replace("CREATE INDEX IF NOT EXISTS", "CREATE INDEX"))

    # Views (e.g. user_held_roles); their SQL is portable.
    for name, sql in lite.execute("SELECT name, sql FROM sqlite_master WHERE type='view'"):
        cur.execute(sql.replace("CREATE VIEW IF NOT EXISTS", "CREATE VIEW"))

    # Append-only audit trail.
    cur.execute("""CREATE FUNCTION audit_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
                   BEGIN RAISE EXCEPTION 'audit_log is append-only'; END $$""")
    for t in APPEND_ONLY:
        if t in meta:
            cur.execute(f"CREATE TRIGGER {q(t + '_append_only')} BEFORE UPDATE OR DELETE ON {q(t)} "
                        f"FOR EACH ROW EXECUTE FUNCTION audit_append_only()")

    pg.commit()
    print(f"Copied {len(meta)} tables, {sum(counts.values())} rows, {fk_count} foreign keys "
          f"into {PG_DSN.split('@')[-1]} schema {SCHEMA}")
    for t in ("users", "user_subjects", "certificate_checks", "audit_log", "audit_log_changes"):
        if t in counts:
            print(f"  {t}: {counts[t]} rows")


if __name__ == "__main__":
    main()
